# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Args',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=5000)),
                ('dislikes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('likes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('ra', models.CharField(max_length=7)),
                ('ram', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=70)),
                ('rg', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=9)),
                ('reason', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='args',
            name='hits',
            field=models.ManyToManyField(related_name='click', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='args',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
