# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=20),
        ),
    ]
