# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160615_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=25),
        ),
    ]
