# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160616_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10001)),
                ('dislikes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('likes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Args')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('hits', models.ManyToManyField(related_name='clicks', to='app.Profile')),
            ],
        ),
    ]
