# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rg',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
